server:
  port: 7071
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/java6AUTHDB
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root

jwt:
  secretKey: ${java6secretkey}
  audience: ${java6audience}
  issuer: ${java6issuer}

rabbitmq:
  exchange-auth: auth-exchange
  registerkey: register-key
  queueRegister: register-queue